# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [70]:
import re
from typing import List

In [71]:
from typing import List

def tokenize_words(text: str) -> List[str]:
    tokens = re.findall(r"\b\w+(?:'\w+)?\b", text)
    return tokens

def tokenize_sentence(text: str) -> List[str]:
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return sentences

text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', "I was supposed to add this text later.Well, it's 10.p.m.", "here, and I'm actually having fun making this course.", ':oI hope you are getting along fine with this presentation, I really did try.And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later', 'Well', "it's", '10', 'p', 'm', 'here', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course', 'oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation', 'I', 'really', 'did', 'try', 'And', 'one', 'last', 'sentence', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [72]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag

file = open("../datasets/trump.txt", "r",encoding="utf-8")
trump = file.read()
words = word_tokenize(trump)
tags = pos_tag(words)
print(tags[:20])
# fill the gap and imports

[('Thank', 'NNP'), ('you', 'PRP'), ('very', 'RB'), ('much', 'RB'), ('.', '.'), ('Mr.', 'NNP'), ('Speaker', 'NNP'), (',', ','), ('Mr.', 'NNP'), ('Vice', 'NNP'), ('President', 'NNP'), (',', ','), ('Members', 'NNP'), ('of', 'IN'), ('Congress', 'NNP'), (',', ','), ('the', 'DT'), ('First', 'NNP'), ('Lady', 'NNP'), ('of', 'IN')]


## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [73]:
import spacy

nlp = spacy.load("en_core_web_sm")

file = open("../datasets/trump.txt", "r",encoding='utf-8')
trump = file.read() 

doc = nlp(trump)
sentences = list(doc.sents)
last_10_sentences = sentences[-10:]

nouns_by_sentence = []

for sent in last_10_sentences:
    nouns = [token.text for token in sent if token.pos_ == "NOUN"]
    nouns_by_sentence.append(nouns)

for i, nouns in enumerate(nouns_by_sentence, start=1):
    print(f"Sentence {i} nouns: {nouns}")
### here comes your code


Sentence 1 nouns: ['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness']
Sentence 2 nouns: ['time', 'thinking']
Sentence 3 nouns: ['time', 'fights']
Sentence 4 nouns: ['courage', 'dreams', 'hearts', 'bravery', 'hopes', 'souls', 'confidence', 'hopes', 'dreams', 'action']
Sentence 5 nouns: ['aspirations', 'fears', 'future', 'failures', 'past', 'vision', 'doubts']
Sentence 6 nouns: ['citizens', 'renewal', 'spirit']
Sentence 7 nouns: ['Members', 'things', 'country']
Sentence 8 nouns: ['tonight', 'moment']
Sentence 9 nouns: ['yourselves', 'future']
Sentence 10 nouns: []


## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [74]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""
    
    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []

    
    def fit_transform(self, corpus: list):
            """Transform list of strings into BoW array."""
            tokenized = []

            for doc in corpus:
                tokens = [token.text.lower() for token in self.__nlp(doc) if token.is_alpha]
                tokenized.append(tokens)

            vocab = sorted(set(word for doc in tokenized for word in doc))
            self.__bow_list = vocab

            matrix = np.zeros((len(corpus), len(vocab)), dtype=int)

            for i, doc in enumerate(tokenized):
                for word in doc:
                    j = vocab.index(word)
                    matrix[i][j] += 1

            return matrix

    def get_feature_names(self) -> list:
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

vectorizer.get_feature_names()
len(vectorizer.get_feature_names())

[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]


31

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [75]:
from nltk.book import *
import random
wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [91]:
def clean_generated(text):
    text = re.sub(r'\s+([.!?])', r'\1', text)
    sentences = re.split('([.!?])', text)
    cleaned = ''
    for i in range(0, len(sentences)-1, 2):
        sentence = sentences[i].strip().capitalize()
        punct = sentences[i+1]
        cleaned += sentence + punct + ' '
    return cleaned.strip()

N=5

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq=None

counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    last_seq = SEP.join(generated.split()[-(N-1):])
    if last_seq not in counts:
        last_seq = random.choice(list(counts.keys()))
        generated += SEP + last_seq
    else:
        generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

# put your code here:
print(generated)
generated = clean_generated(generated)
print(generated)

deterring u.s. high-technology firms appears in today issue of the journal Nature . The finding marks a significant step in research on bulk superconductors which are aimed at use in wires for motors magnets generators and other applications . Scientists had obtained even higher current-carrying capacity in thin films of the new superconductors but have had problems increasing the amount of current that bulk crystals could carry . Superconductors conduct electricity without resistance when cooled . A family of ceramic superconductors discovered during the past three years despite steady sales growth .
Deterring u. S. High-technology firms appears in today issue of the journal nature. The finding marks a significant step in research on bulk superconductors which are aimed at use in wires for motors magnets generators and other applications. Scientists had obtained even higher current-carrying capacity in thin films of the new superconductors but have had problems increasing the amount o